name: flutter_modular
packages:
  - apps/*
  - packages/*

scripts:
  mobile:
    run: melos exec --scope=mobile_app -- flutter run lib/main.dart -d Edge
    description: Run the mobile_app module
  web:
    run: melos exec --scope=web_app -- flutter run lib/main.dart -d Edge
    description: Run the web_app module  



# scripts:
#   get: |
#     melos bootstrap
#   clean: |
#     melos exec -- flutter clean
#   pub_get: |
#     melos exec -- flutter pub get
#   test: |
#     melos exec -- flutter test
#   run:mobile:
#     run: melos exec --scope=mobile_app -- flutter run
#     description: Run the mobile_app module