name: core
description: "A new Flutter package project."
version: 0.0.1
homepage:
resolution: workspace

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  dependency_validator: ^5.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.0.0
  http: ^1.4.0
  # intl: ^0.20.2
  # json_annotation: ^4.9.0
  # path: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  
flutter:

