name: analysis
description: A sample command-line application.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  dart_code_metrics: ^5.7.6

dev_dependencies:

